spring.application.name=personalproject
spring.thymeleaf.cache=false

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ecomerce_db}

spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.access.secret=${JWT_SECRET:VGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgSldUIHNpZ25pbmcgdGhhdCBtdXN0IGJlIGxvbmcgZW5vdWdo}
jwt.access.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:wilbermartcommerce@gmail.com}
spring.mail.password=${MAIL_PASSWORD:cyxp mkaz lvnh auod}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mvc.hiddenmethod.filter.enabled=true
